# Generated by Django 3.1.3 on 2021-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('author', models.CharField(max_length=80, verbose_name='Автор')),
                ('year', models.DateField(verbose_name='Год_выхода_книг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
