# Generated by Django 3.1.3 on 2021-01-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210124_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='years',
        ),
    ]
